<x-filament-panels::page>
<div class="sipma-dashboard-hero"><div><p class="sipma-kicker">{{ auth()->user()->role->getLabel() }} · MABNA SYEKH NAWAWI</p><h2>Selamat bertugas,<br>{{ auth()->user()->name }}.</h2><p>Dampingi kegiatan harian dan pastikan kehadiran kelompok tercatat dengan lengkap.</p>@if(auth()->user()->can('attendances.record'))<a class="sipma-button" href="{{ \App\Filament\Pages\OperationalSessions::getUrl() }}">Isi absensi &nbsp; →</a>@elseif(auth()->user()->hasRole('mudabbir') && auth()->user()->can('sessions.open'))<a class="sipma-button" href="{{ \App\Filament\Pages\OperationalSessions::getUrl() }}">Buka sesi kegiatan &nbsp; →</a>@elseif(auth()->user()->can('users.manage'))<a class="sipma-button" href="{{ \App\Filament\Resources\UserResource::getUrl() }}">Kelola akun & penugasan &nbsp; →</a>@else<a class="sipma-button" href="{{ \App\Filament\Pages\WeeklyReports::getUrl() }}">Pantau laporan &nbsp; →</a>@endif</div><div class="sipma-deadline"><p>Pekan {{ $start->format('d M') }}–{{ $end->format('d M Y') }}</p><strong>Sabtu, 23.59 WIB</strong><p>Absensi biasa terkunci pada {{ $cutoff->format('d F Y') }}. Laporan dapat difinalkan mulai Minggu.</p><a href="{{ \App\Filament\Pages\WeeklyReports::getUrl() }}" class="sipma-button">Lihat laporan →</a></div></div>
<div class="sipma-dashboard-grid"><div><section class="sipma-card"><div class="sipma-section-head"><h2>Kegiatan hari ini</h2><span class="sipma-kicker">{{ now()->format('d M Y') }}</span></div>
@forelse($todaySessions as $session)<div class="sipma-row"><div><strong>{{ $session->activity->name }}</strong><small>{{ $session->group->name }} · {{ $session->starts_at }}–{{ $session->ends_at }} WIB</small></div><x-status-badge :status="$session->status"/><a class="sipma-button sipma-secondary" href="{{ \App\Filament\Pages\OperationalSessions::getUrl(['session' => $session->id]) }}">{{ auth()->user()->can('attendances.record') ? 'Isi absensi' : 'Lihat sesi' }} →</a></div>@empty<div class="sipma-empty"><strong>Belum ada sesi hari ini</strong>Sesi akan tampil setelah mudabbir membukanya.</div>@endforelse</section>
<section class="sipma-card"><h2>Kelengkapan absensi pekan ini</h2>@forelse($completion as $item)<div class="sipma-row" style="display:block"><div class="sipma-section-head"><div><strong>{{ $item['group']->name }}</strong><small>{{ $item['sessions'] }} sesi · {{ $item['recorded'] }} dari {{ $item['expected'] }} kehadiran tercatat</small></div><x-status-badge :status="$item['percentage'] === null ? 'draft' : ($item['percentage'] === 100.0 ? 'APPROVED' : 'PENDING')"/></div>@if($item['percentage'] !== null)<div class="sipma-progress" role="progressbar" aria-label="Kelengkapan {{ $item['group']->name }}" aria-valuenow="{{ $item['percentage'] }}" aria-valuemin="0" aria-valuemax="100"><span style="width:{{ $item['percentage'] }}%"></span></div>@endif</div>@empty<div class="sipma-empty"><strong>Belum ada kelompok tugas</strong>Hubungi admin untuk melengkapi penugasan.</div>@endforelse</section></div>
<aside><section class="sipma-card"><h2>Perlu dilengkapi</h2>@forelse($incomplete->take(8) as $session)<div class="sipma-row"><div><strong>{{ $session->group->name }}</strong><small>{{ $session->date->format('d/m') }} · {{ $session->activity->name }}</small><small>{{ count($session->roster ?? []) - $session->attendances->count() }} mahasantri belum diisi</small></div><a class="sipma-button sipma-secondary" href="{{ \App\Filament\Pages\OperationalSessions::getUrl(['session' => $session->id]) }}">Buka →</a></div>@empty<div class="sipma-empty"><strong>Tidak ada sesi tertunda</strong>Kegiatan yang belum dibuka belum dihitung.</div>@endforelse</section><section class="sipma-card"><h2>Laporan terbit</h2>@forelse($reports as $period)<div class="sipma-row"><div><strong>{{ $period->group->name }}</strong><small>{{ $period->starts_on->format('d M') }}–{{ $period->ends_on->format('d M') }} · Versi {{ $period->current_version }}</small></div><x-status-badge :status="$period->current_version > 1 ? 'revisi' : 'final'"/></div>@empty<p class="sipma-muted">Belum ada laporan final. Siapkan absensi lengkap sebelum batas Sabtu.</p>@endforelse</section></aside></div>
@hasanyrole('murabbi|pengasuh')
<section class="sipma-card"><h2>Performa mudabbir pada pekan ini</h2><p class="sipma-muted">Aktivitas pada sesi kelompok binaan, bukan nilai atau peringkat otomatis.</p><div class="sipma-scroll"><table class="sipma-table"><thead><tr><th>Mudabbir</th><th>Kelompok</th><th>Absensi dicatat</th><th>Absensi direvisi terakhir</th><th>Pengajuan direview</th></tr></thead><tbody>@forelse($staffPerformance as $staff)<tr><td>{{ $staff['name'] }}<br>{{ $staff['role'] }}</td><td>{{ $staff['groups'] }}</td><td>{{ $staff['recorded'] }}</td><td>{{ $staff['revised'] }}</td><td>{{ $staff['reviews'] }}</td></tr>@empty<tr><td colspan="5">Belum ada mudabbir dalam kelompok binaan.</td></tr>@endforelse</tbody></table></div><p class="sipma-muted">Murabbi memantau kelompok, absensi, perkembangan mahasantri dan laporan, serta mereview koreksi mudabbir. Pengisian absensi dilakukan mudabbir.</p></section>
@endhasanyrole
@if(\App\Filament\Pages\GroupAssignments::canAccess())<a class="sipma-button sipma-secondary" href="{{ \App\Filament\Pages\GroupAssignments::getUrl() }}">Bagi mahasantri ke kelompok →</a>@endif
</x-filament-panels::page>
